apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: wysh6mhmg-nodejs 
  janus-idp.io/tekton: wysh6mhmg-nodejs
  backstage.io/kubernetes-id: wysh6mhmg-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: wysh6mhmg-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml